extends:
  - airbnb-base
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:prettier/recommended
globals:
  SHOMOP_CONF: writable
rules:
  import/extensions:
    - error
    - always
    - js: never
      json: never
      vue: never
  prettier/prettier: 1
  no-alert: 0
  func-names: 0
  default-case: 0
  no-case-declarations: 1
  import/prefer-default-export: 0
  no-prototype-builtins: 1
  no-param-reassign: 0
  prefer-destructuring: 0
  no-unused-expressions: 0
  no-else-return: 0
  no-shadow: 0
  global-require: 0
  no-console: 0
  no-underscore-dangle: 0
  no-nested-ternary: 0
  no-plusplus: 0
  no-restricted-syntax: 0
  prefer-const: 0
  consistent-return: 0
  array-callback-return: 0
  linebreak-style: 0
  no-multi-assign: 1
  multiline-comment-style: 0
  max-len:
    - 1
    - code: 80
      ignoreComments: true
      ignoreTrailingComments: true
      ignoreUrls: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
      ignoreRegExpLiterals: true
